version: '3.8'

services:
  internship-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    container_name: ${DC_CONTAINER_NAME}
    ports:
      - ${DC_APP_PORT}:3000
    environment:
      NODE_ENV: staging
      NUXT_PUBLIC_SYSTEM_IDENTIFIER: ${NUXT_PUBLIC_SYSTEM_IDENTIFIER}
      NUXT_PRIVATE_USER_AUTH_API_URL: ${NUXT_PRIVATE_USER_AUTH_API_URL}
      NUXT_PRIVATE_USER_PROFILE_API_URL: ${NUXT_PRIVATE_USER_PROFILE_API_URL}
      NUXT_PRIVATE_REF_HR_API_URL: ${NUXT_PRIVATE_REF_HR_API_URL}
      NUXT_PRIVATE_REF_GENERIC_API_URL: ${NUXT_PRIVATE_REF_GENERIC_API_URL}
      NUXT_PRIVATE_INTERNSHIP_API_URL: ${NUXT_PRIVATE_INTERNSHIP_API_URL}
      # SYSTEM_IDENTIFIER: internship_hash
      # USER_AUTH_API_URL: 10.9.206.193:5003
      # USER_PROFILE_API_URL: 10.9.206.193:5004
      # REF_GENERIC_API_URL: 10.9.206.193:5008
      # REF_HR_API_URL: 10.9.206.193:5011
    restart: unless-stopped
